title: SMR Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.sarveshmrao.in
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Homepage
      description: Homepage (sarveshmrao.in).
      category: Uncategorized
    - name: Blog
      description: SMR Blog (blog.sarveshmrao.in).
      category: Uncategorized
    - name: CDN
      description: CDN for static files like Logos etc (cdn.sarveshmrao.in).
      category: Uncategorized
    - name: Forum
      description: Community Forum for support on SMR Services (forums.sarveshmrao.in).
      category: Uncategorized
    - name: CloudFlare
      category: Uncategorized
      description: CloudFlare is our DDoS protection provider and proxies all our
        traffic through their network
    - name: Machan
      category: Discord Bots
      description: A all in one Discord Bot created to be used in many servers.
    - name: SMR Bot
      description: SMR Bot is an all rounder bot for Discord
      category: Discord Bots
    - name: FeedIt
      category: Discord Bots
      description: A Discord Bot for delivering articles from RSS Feed.
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/smr-word-original-removebg-preview.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      closed: false
      untitled: true
    - name: Discord Bots
      description: Bots designed by Sarvesh M Rao.
      closed: true
      untitled: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
