title: SMR Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.sarveshmrao.in
params:
  disableDarkMode: false
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: Homepage
      description: Homepage (sarveshmrao.in).
      category: Uncategorized
    - name: Forum
      description: Community Forum for support on SMR Services (forum.sarveshmrao.in).
      category: Uncategorized
    - name: CDN
      description: CDN for static files like Logos etc (cdn.sarveshmrao.in).
      category: Heartbeat
    - name: CloudFlare
      category: Heartbeat
      description: CloudFlare is our DDoS protection provider and proxies all our
        traffic through their network
    - name: Machan
      category: Discord Bots
      description: A all in one Discord Bot created to be used in many servers.
    - name: SMR Bot
      description: SMR Bot is an all rounder bot for Discord
      category: Discord Bots
    - name: FeedIt
      category: Discord Bots
      description: A Discord Bot for delivering articles from RSS Feed.
    - name: SMR Ads
      category: Heartbeat
      description: Responsible for delivering ads across SMR Sites, Products and
        Services. (For internal use)
    - name: SMR Analytics
      category: Heartbeat
      description: Responsible for creating analytics for SMR Sites, Services,
        Products. This being down might slow down load time of site. (For
        internal use)
    - name: Site Server
      category: Heartbeat
      description: Server which hosts all the SMR sites. (For internal use)
    - name: Bot Server
      category: Heartbeat
      description: Server which hosts all the SMR Bots. (For internal use)
    - name: SMR Docs
      category: Uncategorized
      description: Documentation site for SMR Services and Products. (docs.sarveshmrao.in)
    - name: FeedIt Site
      category: Uncategorized
      description: Control Panel for the FeedIt Discord Bot. (feedit.sarveshmrao.in)
    - name: SMR Accounts
      category: Uncategorized
      description: The Identity Provider responsible for logging into all the SMR Services
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: /img/smr-word-original-removebg-preview.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  customTabs: []
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Uncategorized
      closed: false
      untitled: true
    - name: Heartbeat
      description: "All these should be up for SMR Sites, Services, Products to run
        without any issues. "
      closed: true
    - name: Discord Bots
      description: Bots designed by Sarvesh M Rao.
      closed: true
      untitled: false
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
useRelativeTime: true
  # Should relative time (x min ago) be used?
  #
  # IMPORTANT: In the frontmatter, the dates MUST be in
  # the UTC time zone for this to work preperly. If you 
  # use Netlify CMS, all good — the CMS picks UTC time
  # by default. Otherwise, there may be very inaccurate
  # times if multiple time zones are in your issue files.
  #
  # FOR YOUR CONSIDERATION: This feature was introduced in
  # v5. It may be a breaking change in the case when you
  # wish to use relative time but old issues do not have
  # UTC time (and therefore are out of sync by ±24 hours)
  #
  # Read the wiki for more: 
  # https://github.com/cstate/cstate/wiki/Customization#time 
  #
  # If enabled, will display relative times in places like
  # the incident history and summaries instead of using
  # dateFormat and shortDateFormat (except for if you use
  # the old shortcode).
  #
  # Default: `true`
  # BOOLEAN; `true`, `false`
  useRelativeTime: true

  # If enabled, doesn't show seconds on relative times.
  #
  # With option ON (true):
  # "Last checked <1 min ago"
  #
  # With option OFF (false; default):
  # "Last checked 20s ago"
  #
  # Default: `false`
  # BOOLEAN; `true`, `false`
  skipSeconds: false

  # Should there be an automatic "Last updated"
  # text shown below issues?
  #
  # Default: `true`
  # BOOLEAN; `true`, `false`
  enableLastMod: true
